### ISSUE TITLE
ERROR : processes not found

### ISSUE THREAD

**Issue by mightytyphoon** [ionic-team/native-run#38] opened 2019-06-06 16:56 UTC
Hi Folks, 
On running ``ionic cordova emulate android`` it looks like some processes are not found :

```
Erreur�: le processus "9244" est introuvable. (translation : process 9244 not found)
Erreur�: le processus "11276" est introuvable.
Erreur�: le processus "15912" est introuvable.
```

Full Output :
```
ionic cordova emulate android --target=Nexus_5X_API_29 --verbose
...
// skipping output because all works fine and build is done.
...
BUILD SUCCESSFUL in 10s
42 actionable tasks: 42 up-to-date

D:\Work\benzaiten\mobile-app\benzaiten>if "0" == "0" goto mainEnd

D:\Work\benzaiten\mobile-app\benzaiten>if "Windows_NT" == "Windows_NT" endlocal
Command finished with error code 0: D:\Work\benzaiten\mobile-app\benzaiten\platforms\android\gradlew cdvBuildDebug,-b,D:\Work\benzaiten\mobile-app\benzaiten\platforms\android\build.gradle
Built the following apk(s):
        D:\Work\benzaiten\mobile-app\benzaiten\platforms\android\app\build\outputs\apk\debug\app-debug.apk
No scripts found for hook "after_compile".
No scripts found for hook "after_build".
// native-run starts here
> native-run.cmd android --app platforms\android\app\build\outputs\apk\debug\app-debug.apk --target Nexus_5X_API_29 --verbose
2019-06-06T16:43:38.173Z native-run:android:utils:sdk:resolveSDKRoot Looking for $ANDROID_HOME
2019-06-06T16:43:38.177Z native-run:android:utils:sdk:resolveSDKRoot Looking for $ANDROID_SDK_ROOT
2019-06-06T16:43:38.180Z native-run:android:utils:sdk:resolveSDKRoot Using $ANDROID_SDK_ROOT at C:\Users\laurent\AppData\Local\Android\Sdk
2019-06-06T16:43:38.181Z native-run:android:utils:sdk:resolveEmulatorHome Looking for $ANDROID_EMULATOR_HOME
2019-06-06T16:43:38.181Z native-run:android:utils:sdk:resolveEmulatorHome Using $HOME/.android/ at C:\Users\laurent\.android
2019-06-06T16:43:38.181Z native-run:android:utils:sdk:resolveAVDHome Looking for $ANDROID_AVD_HOME
2019-06-06T16:43:38.181Z native-run:android:utils:sdk:resolveAVDHome Using $HOME/.android/avd/ at C:\Users\laurent\.android\avd
2019-06-06T16:43:38.182Z native-run:android:utils:sdk:getSDKPackage Parsing C:\Users\laurent\AppData\Local\Android\Sdk\platform-tools\package.xml
2019-06-06T16:43:38.218Z native-run:android:utils:adb:getDevices Invoking adb: 'C:\\Users\\laurent\\AppData\\Local\\Android\\Sdk\\platform-tools/adb' [ 'devices', '-l' ]
2019-06-06T16:43:38.270Z native-run:android:utils:adb:parseAdbDevices Parsing adb devices from output lines: [ 'List of devices attached',
  'emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:6',
  '',
  '' ]
2019-06-06T16:43:38.272Z native-run:android:utils:adb:getDeviceProperties Invoking adb: 'C:\\Users\\laurent\\AppData\\Local\\Android\\Sdk\\platform-tools/adb' [ '-s', 'emulator-5554', 'shell', 'getprop' ]
2019-06-06T16:43:38.419Z native-run Caught fatal error: { Error: Command failed: C:\Users\laurent\AppData\Local\Android\Sdk\platform-tools/adb -s emulator-5554 shell getprop

    at ChildProcess.exithandler (child_process.js:297:12)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:984:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
  killed: false,
  code: 3221226356,
  signal: null,
  cmd:
   'C:\\Users\\laurent\\AppData\\Local\\Android\\Sdk\\platform-tools/adb -s emulator-5554 shell getprop',
  stdout:
   '[dalvik.vm.appimageformat]: [lz4]\r\n[dalvik.vm.dex2oat-Xms]: [64m]\r\n[dalvik.vm.dex2oat-Xmx]: [512m]\r\n[dalvik.vm.dex2oat-minidebuginfo]: [true]\r\n[dalvik.vm.dex2oat-resolve-startup-strings]: [true]\r\n[dalvik.vm.dexopt.secondary]: [true]\r\n[dalvik.vm.heapsize]: [512m]\r\n[dalvik.vm.image-dex2oat-Xms]: [64m]\r\n[dalvik.vm.image-dex2oat-Xmx]: [64m]\r\n[dalvik.vm.isa.x86.features]: [default]\r\n[dalvik.vm.isa.x86.variant]: [x86]\r\n[dalvik.vm.minidebuginfo]: [true]\r\n[dalvik.vm.usejit]: [true]\r\n[dalvik.vm.usejitprofiles]: [true]\r\n[debug.atrace.tags.enableflags]: [0]\r\n[debug.force_rtl]: [false]\r\n[debug.hwui.renderer]: [skiagl]\r\n[dev.bootcomplete]: [1]\r\n[dev.mnt.blk.data]: [vdc]\r\n[drm.service.enabled]: [true]\r\n[gsm.current.phone-type]: [1]\r\n[gsm.defaultpdpcontext.active]: [true]\r\n[gsm.network.type]: [LTE]\r\n[gsm.operator.alpha]: [Android]\r\n[gsm.operator.iso-country]: [us]\r\n[gsm.operator.isroaming]: [false]\r\n[gsm.operator.numeric]: [310260]\r\n[gsm.sim.operator.alpha]: [T-Mobile]\r\n[gsm.sim.operator.iso-country]: [us]\r\n[gsm.sim.operator.numeric]: [310260]\r\n[gsm.sim.state]: [LOADED]\r\n[gsm.version.baseband]: [1.0.0.0]\r\n[gsm.version.ril-impl]: [android reference-ril 1.0]\r\n[hwservicemanager.ready]: [true]\r\n[init.svc.adbd]: [running]\r\n[init.svc.apexd]: [running]\r\n[init.svc.apexd-bootstrap]: [stopped]\r\n[init.svc.ashmemd]: [running]\r\n[init.svc.audioserver]: [running]\r\n[init.svc.bootanim]: [stopped]\r\n[init.svc.bpfloader]: [stopped]\r\n[init.svc.broadcastradio-hal]: [running]\r\n[init.svc.cameraserver]: [running]\r\n[init.svc.dhcpclient_rtr]: [running]\r\n[init.svc.dhcpserver]: [running]\r\n[init.svc.drm]: [running]\r\n[init.svc.emu_hostapd]: [running]\r\n[init.svc.gatekeeperd]: [running]\r\n[init.svc.goldfish-logcat]: [running]\r\n[init.svc.gpu]: [running]\r\n[init.svc.healthd]: [running]\r\n[init.svc.hidl_memory]: [running]\r\n[init.svc.hwservicemanager]: [running]\r\n[init.svc.idmap2d]: [running]\r\n[init.svc.incidentd]: [running]\r\n[init.svc.installd]: [running]\r\n[init.svc.iorapd]: [stopped]\r\n[init.svc.ipv6proxy]: [running]\r\n[init.svc.keystore]: [running]\r\n[init.svc.lmkd]: [running]\r\n[init.svc.logd]: [running]\r\n[init.svc.logd-auditctl]: [stopped]\r\n[init.svc.logd-reinit]: [stopped]\r\n[init.svc.mdnsd]: [running]\r\n[init.svc.media]: [running]\r\n[init.svc.media.swcodec]: [running]\r\n[init.svc.mediadrm]: [running]\r\n[init.svc.mediaextractor]: [running]\r\n[init.svc.mediametrics]: [running]\r\n[init.svc.netd]: [running]\r\n[init.svc.netmgr]: [running]\r\n[init.svc.qemu-props]: [running]\r\n[init.svc.ranchu-net]: [stopped]\r\n[init.svc.ranchu-setup]: [stopped]\r\n[init.svc.servicemanager]: [running]\r\n[init.svc.statsd]: [running]\r\n[init.svc.storaged]: [running]\r\n[init.svc.surfaceflinger]: [running]\r\n[init.svc.system_suspend]: [running]\r\n[init.svc.tombstoned]: [running]\r\n[init.svc.traced]: [running]\r\n[init.svc.traced_probes]: [running]\r\n[init.svc.ueventd]: [running]\r\n[init.svc.update_verifier_nonencrypted]: [stopped]\r\n[init.svc.usbd]: [stopped]\r\n[init.svc.vndservicemanager]: [running]\r\n[init.svc.vold]: [running]\r\n[init.svc.wificond]: [running]\r\n[init.svc.wpa_supplicant]: [running]\r\n[init.svc.zygote]: [running]\r\n[log.tag.APM_AudioPolicyManager]: [D]\r\n[log.tag.stats_log]: [I]\r\n[media.mediadrmservice.enable]: [true]\r\n[net.bt.name]: [Android]\r\n[net.qtaguid_enabled]: [1]\r\n[net.tcp.default_init_rwnd]: [60]\r\n[persist.sys.boot.reason]: []\r\n[persist.sys.boot.reason.history]: [reboot,1559839171\r\nreboot,factory_reset,1559836563\r\nreboot,1559836507]\r\n[persist.sys.dalvik.vm.lib.2]: [libart.so]\r\n[persist.sys.disable_rescue]: [true]\r\n[persist.sys.displayinset.top]: [0]\r\n[persist.sys.gps.lpp]: [0]\r\n[persist.sys.isolated_storage]: [true]\r\n[persist.sys.timezone]: [GMT]\r\n[persist.sys.usb.config]: [adb]\r\n[persist.sys.zram_enabled]: [1]\r\n[persist.traced.enable]: [1]\r\n[pm.dexopt.ab-ota]: [speed-profile]\r\n[pm.dexopt.bg-dexopt]: [speed-profile]\r\n[pm.dexopt.boot]: [verify]\r\n[pm.dexopt.first-boot]: [quicken]\r\n[pm.dexopt.inactive]: [verify]\r\n[pm.dexopt.install]: [speed-profile]\r\n[pm.dexopt.shared]: [speed]\r\n[qemu.adb.secure]: [1]\r\n[qemu.gles]: [1]\r\n[qemu.hw.mainkeys]: [0]\r\n[qemu.logcat]: [start]\r\n[qemu.sf.fake_camera]: [front]\r\n[qemu.sf.lcd_density]: [420]\r\n[qemu.timezone]: [Unknown/Unknown]\r\n[ro.actionable_compatible_property.enabled]: [true]\r\n[ro.adb.secure]: [1]\r\n[ro.allow.mock.location]: [0]\r\n[ro.apex.updatable]: [true]\r\n[ro.baseband]: [unknown]\r\n[ro.board.platform]: []\r\n[ro.boot.android_dt_dir]: [/proc/device-tree/firmware/android/]\r\n[ro.boot.bootreason]: [reboot]\r\n[ro.boot.hardware]: [ranchu]\r\n[ro.boot.serialno]: [EMULATOR29X0X11X0]\r\n[ro.boot.verifiedbootstate]: [orange]\r\n[ro.boot.veritymode]: [enforcing]\r\n[ro.bootloader]: [unknown]\r\n[ro.bootmode]: [unknown]\r\n[ro.build.ab_update]: [true]\r\n[ro.build.characteristics]: [emulator]\r\n[ro.build.date]: [Thu May 30 01:17:52 UTC 2019]\r\n[ro.build.date.utc]: [1559179072]\r\n[ro.build.description]: [sdk_gphone_x86-user 10 QPP4.190502.018 5616371 release-keys]\r\n[ro.build.display.id]: [QPP4.190502.018]\r\n[ro.build.fingerprint]: [google/sdk_gphone_x86/generic_x86:10/QPP4.190502.018/5616371:user/release-keys]\r\n[ro.build.flavor]: [sdk_gphone_x86-user]\r\n[ro.build.host]: [wphn1.hot.corp.google.com]\r\n[ro.build.id]: [QPP4.190502.018]\r\n[ro.build.product]: [generic_x86]\r\n[ro.build.system_root_image]: [true]\r\n[ro.build.tags]: [release-keys]\r\n[ro.build.type]: [user]\r\n[ro.build.user]: [android-build]\r\n[ro.build.version.all_codenames]: [REL]\r\n[ro.build.version.base_os]: []\r\n[ro.build.version.codename]: [REL]\r\n[ro.build.version.incremental]: [5616371]\r\n[ro.build.version.min_supported_target_sdk]: [23]\r\n[ro.build.version.preview_sdk]: [0]\r\n[ro.build.version.preview_sdk_fingerprint]: [REL]\r\n[ro.build.version.release]: [10]\r\n[ro.build.version.sdk]: [29]\r\n[ro.build.version.security_patch]: [2019-06-05]\r\n[ro.carrier]: [unknown]\r\n[ro.com.google.ime.theme_id]: [5]\r\n[ro.com.google.locationfeatures]: [1]\r\n[ro.config.alarm_alert]: [Alarm_Classic.ogg]\r\n[ro.config.notification_sound]: [OnTheHunt.ogg]\r\n[ro.config.ringtone]: [Ring_Synth_04.ogg]\r\n[ro.control_privapp_permissions]: [enforce]\r\n[ro.cp_system_other_odex]: [0]\r\n[ro.crypto.state]: [encrypted]\r\n[ro.crypto.type]: [file]\r\n[ro.dalvik.vm.native.bridge]: [0]\r\n[ro.debuggable]: [0]\r\n[ro.device_owner]: [false]\r\n[ro.gfx.angle.supported]: [true]\r\n[ro.hardware]: [ranchu]\r\n[ro.hardware.audio.primary]: [goldfish]\r\n[ro.hardware.egl]: [emulation]\r\n[ro.hardware.power]: [ranchu]\r\n[ro.hwui.use_vulkan]: []\r\n[ro.iorapd.enable]: [false]\r\n[ro.kernel.PARTUUID]: [0BB07748-8A52-4FE4-8AD2-933F0564488B]\r\n[ro.kernel.android.checkjni]: [1]\r\n[ro.kernel.android.qemud]: [1]\r\n[ro.kernel.androidboot.android_dt_dir]: [/proc/device-tree/firmware/android/]\r\n[ro.kernel.androidboot.hardware]: [ranchu]\r\n[ro.kernel.androidboot.serialno]: [EMULATOR29X0X11X0]\r\n[ro.kernel.androidboot.verifiedbootstate]: [orange]\r\n[ro.kernel.androidboot.veritymode]: [enforcing]\r\n[ro.kernel.clocksource]: [pit]\r\n[ro.kernel.cma]: [288M@0-4G]\r\n[ro.kernel.console]: [0]\r\n[ro.kernel.dm]: ["1]\r\n[ro.kernel.init]: [/init]\r\n[ro.kernel.loop.max_part]: [7]\r\n[ro.kernel.mac80211_hwsim.channels]: [2]\r\n[ro.kernel.mac80211_hwsim.mac_prefix]: [5554]\r\n[ro.kernel.memmap]: [0x10000$0xff018000]\r\n[ro.kernel.ndns]: [4]\r\n[ro.kernel.qemu]: [1]\r\n[ro.kernel.qemu.dalvik.vm.heapsize]: [512m]\r\n[ro.kernel.qemu.encrypt]: [1]\r\n[ro.kernel.qemu.gles]: [1]\r\n[ro.kernel.qemu.opengles.version]: [196608]\r\n[ro.kernel.qemu.settings.system.screen_off_timeout]: [2147483647]\r\n[ro.kernel.qemu.uirenderer]: [skiagl]\r\n[ro.kernel.qemu.wifi]: [1]\r\n[ro.kernel.ramoops.mem_address]: [0xff018000]\r\n[ro.kernel.ramoops.mem_size]: [0x10000]\r\n[ro.kernel.root]: [/dev/dm-0]\r\n[ro.lmk.log_stats]: [true]\r\n[ro.logd.size.stats]: [64K]\r\n[ro.nnapi.extensions.deny_on_product]: [true]\r\n[ro.opa.eligible_device]: [true]\r\n[ro.opengles.version]: [196608]\r\n[ro.postinstall.fstab.prefix]: [/system]\r\n[ro.product.board]: [goldfish_x86]\r\n[ro.product.brand]: [google]\r\n[ro.product.cpu.abi]: [x86]\r\n[ro.product.cpu.abilist]: [x86]\r\n[ro.product.cpu.abilist32]: [x86]\r\n[ro.product.cpu.abilist64]: []\r\n[ro.product.device]: [generic_x86]\r\n[ro.product.first_api_level]: [28]\r\n[ro.product.locale]: [en-US]\r\n[ro.product.manufacturer]: [Google]\r\n[ro.product.model]: [Android SDK built for x86]\r\n[ro.product.name]: [sdk_gphone_x86]\r\n[ro.product.system.brand]: [google]\r\n[ro.product.system.device]: [generic_x86]\r\n[ro.product.system.manufacturer]: [Google]\r\n[ro.product.system.model]: [Android SDK built for x86]\r\n[ro.product.system.name]: [sdk_gphone_x86]\r\n[ro.product.vendor.brand]: [google]\r\n[ro.product.vendor.device]: [generic_x86]\r\n[ro.product.vendor.manufacturer]: [Google]\r\n[ro.product.vendor.model]: [Android SDK built for x86]\r\n[ro.product.vendor.name]: [sdk_gphone_x86]\r\n[ro.property_service.version]: [2]\r\n[ro.revision]: [0]\r\n[ro.secure]: [1]\r\n[ro.serialno]: [EMULATOR29X0X11X0]\r\n[ro.setupwizard.mode]: [DISABLED]\r\n[ro.storage_manager.enabled]: [true]\r\n[ro.system.build.date]: [Thu May 30 01:17:52 UTC 2019]\r\n[ro.system.build.date.utc]: [1559179072]\r\n[ro.system.build.fingerprint]: [google/sdk_gphone_x86/generic_x86:10/QPP4.190502.018/5616371:user/release-keys]\r\n[ro.system.build.id]: [QPP4.190502.018]\r\n[ro.system.build.tags]: [release-keys]\r\n[ro.system.build.type]: [user]\r\n[ro.system.build.version.incremental]: [5616371]\r\n[ro.system.build.version.release]: [10]\r\n[ro.system.build.version.sdk]: [29]\r\n[ro.treble.enabled]: [true]\r\n[ro.vendor.build.date]: [Thu May 30 01:17:52 UTC 2019]\r\n[ro.vendor.build.date.utc]: [1559179072]\r\n[ro.vendor.build.fingerprint]: [google/sdk_gphone_x86/generic_x86:10/QPP4.190502.018/5616371:user/release-keys]\r\n[ro.vendor.build.security_patch]: []\r\n[ro.vndk.version]: [29]\r\n[ro.wifi.channels]: []\r\n[ro.zygote]: [zygote32]\r\n[ro.zygote.disable_gl_preload]: [true]\r\n[security.perf_harden]: [1]\r\n[selinux.restorecon_recursive]: [/data/misc_ce/0]\r\n[service.bootanim.exit]: [1]\r\n[service.sf.present_timestamp]: [1]\r\n[setupwizard.feature.baseline_setupwizard_enabled]: [true]\r\n[sys.boot.reason]: [reboot]\r\n[sys.boot.reason.last]: [reboot]\r\n[sys.boot_completed]: [1]\r\n[sys.isolated_storage_snapshot]: [true]\r\n[sys.logbootcomplete]: [1]\r\n[sys.retaildemo.enabled]: [0]\r\n[sys.sysctl.extra_free_kbytes]: [24300]\r\n[sys.sysctl.tcp_def_init_rwnd]: [60]\r\n[sys.system_server.start_count]: [1]\r\n[sys.system_server.start_elapsed]: [15318]\r\n[sys.system_server.start_uptime]: [15318]\r\n[sys.usb.config]: [adb]\r\n[sys.usb.configfs]: [0]\r\n[sys.usb.state]: [adb]\r\n[sys.use_memfd]: [false]\r\n[sys.user.0.ce_available]: [true]\r\n[sys.wifitracing.started]: [1]\r\n[vendor.qemu.dev.bootcomplete]: [1]\r\n[vold.has_adoptable]: [1]\r\n[vold.has_quota]: [1]\r\n[vold.has_reserved]: [1]\r\n[vold.post_fs_data_done]: [1]\r\n[wifi.direct.interface]: [p2p-dev-wlan0]\r\n[wifi.interface]: [wlan0]\r\n',
  stderr: '' }
Error: Command failed: C:\Users\laurent\AppData\Local\Android\Sdk\platform-tools/adb -s emulator-5554 shell getprop

    at ChildProcess.exithandler (child_process.js:297:12)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:984:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
[ERROR] An error occurred while running subprocess native-run.

        native-run.cmd android --app platforms\android\app\build\outputs\apk\debug\app-d... exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
  ionic:utils-process onBeforeExit handler: 'process.exit' received +0ms
  ionic:utils-process onBeforeExit handler: running 3 functions +0ms
  ionic:utils-process error while killing process tree for 9244: { Error: Command failed: taskkill /pid 9244 /T /F
  ionic:utils-process Erreur�: le processus "9244" est introuvable.
  ionic:utils-process 
  ionic:utils-process     at ChildProcess.exithandler (child_process.js:297:12)
  ionic:utils-process     at ChildProcess.emit (events.js:197:13)
  ionic:utils-process     at maybeClose (internal/child_process.js:984:16)
  ionic:utils-process     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
  ionic:utils-process   killed: false,
  ionic:utils-process   code: 128,
  ionic:utils-process   signal: null,
  ionic:utils-process   cmd: 'taskkill /pid 9244 /T /F' } +179ms
  ionic:utils-process onBeforeExit handler: error from function: { Error: Command failed: taskkill /pid 9244 /T /F
  ionic:utils-process Erreur�: le processus "9244" est introuvable.
  ionic:utils-process 
  ionic:utils-process     at ChildProcess.exithandler (child_process.js:297:12)
  ionic:utils-process     at ChildProcess.emit (events.js:197:13)
  ionic:utils-process     at maybeClose (internal/child_process.js:984:16)
  ionic:utils-process     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
  ionic:utils-process   killed: false,
  ionic:utils-process   code: 128,
  ionic:utils-process   signal: null,
  ionic:utils-process   cmd: 'taskkill /pid 9244 /T /F' } +1ms
  ionic:utils-process error while killing process tree for 11276: { Error: Command failed: taskkill /pid 11276 /T /F
  ionic:utils-process Erreur�: le processus "11276" est introuvable.
  ionic:utils-process 
  ionic:utils-process     at ChildProcess.exithandler (child_process.js:297:12)
  ionic:utils-process     at ChildProcess.emit (events.js:197:13)
  ionic:utils-process     at maybeClose (internal/child_process.js:984:16)
  ionic:utils-process     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
  ionic:utils-process   killed: false,
  ionic:utils-process   code: 128,
  ionic:utils-process   signal: null,
  ionic:utils-process   cmd: 'taskkill /pid 11276 /T /F' } +14ms
  ionic:utils-process onBeforeExit handler: error from function: { Error: Command failed: taskkill /pid 11276 /T /F
  ionic:utils-process Erreur�: le processus "11276" est introuvable.
  ionic:utils-process 
  ionic:utils-process     at ChildProcess.exithandler (child_process.js:297:12)
  ionic:utils-process     at ChildProcess.emit (events.js:197:13)
  ionic:utils-process     at maybeClose (internal/child_process.js:984:16)
  ionic:utils-process     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
  ionic:utils-process   killed: false,
  ionic:utils-process   code: 128,
  ionic:utils-process   signal: null,
  ionic:utils-process   cmd: 'taskkill /pid 11276 /T /F' } +2ms
  ionic:utils-process error while killing process tree for 15912: { Error: Command failed: taskkill /pid 15912 /T /F
  ionic:utils-process Erreur�: le processus "15912" est introuvable.
  ionic:utils-process 
  ionic:utils-process     at ChildProcess.exithandler (child_process.js:297:12)
  ionic:utils-process     at ChildProcess.emit (events.js:197:13)
  ionic:utils-process     at maybeClose (internal/child_process.js:984:16)
  ionic:utils-process     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
  ionic:utils-process   killed: false,
  ionic:utils-process   code: 128,
  ionic:utils-process   signal: null,
  ionic:utils-process   cmd: 'taskkill /pid 15912 /T /F' } +3ms
  ionic:utils-process onBeforeExit handler: error from function: { Error: Command failed: taskkill /pid 15912 /T /F
  ionic:utils-process Erreur�: le processus "15912" est introuvable.
  ionic:utils-process 
  ionic:utils-process     at ChildProcess.exithandler (child_process.js:297:12)
  ionic:utils-process     at ChildProcess.emit (events.js:197:13)
  ionic:utils-process     at maybeClose (internal/child_process.js:984:16)
  ionic:utils-process     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
  ionic:utils-process   killed: false,
  ionic:utils-process   code: 128,
  ionic:utils-process   signal: null,
  ionic:utils-process   cmd: 'taskkill /pid 15912 /T /F' } +1ms
  ionic:utils-process processExit: exiting (exit code: 1) +0ms
```

**Comment by mightytyphoon** [comment] 2019-06-06 17:03
may be related with https://github.com/ionic-team/ionic-cli/issues/4011

**Comment by mightytyphoon** [comment] 2019-06-06 17:20
# Temporaly Fixed by Downgrading platform-tools

more infos here : https://github.com/flutter/flutter/issues/33938#issuecomment-499250288

**Comment by dwieeb** [comment] 2019-06-06 21:24
Having errors in verbose log output doesn't always mean something is broken.

The real issue here is that the `adb -s emulator-5554 shell getprop` command failed, but that appears to be a duplicate of https://github.com/ionic-team/ionic-cli/issues/4011

**Closed by dwieeb** 2019-06-06 21:24 UTC

**Comment by XamrinIndian** [comment] 2019-06-14 09:55
BUILD SUCCESSFUL in 11s
42 actionable tasks: 42 up-to-date
Built the following apk(s):
        D:\beauty_JH\bj\platforms\android\app\build\outputs\apk\debug\app-debug.
apk
> native-run.cmd android --app platforms\android\app\build\outputs\apk\debug\app
-debug.apk
Error: Command failed: C:\Users\xamrin\AppData\Local\Android\Sdk\platform-tools\
adb devices -l

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:606:12)
[ERROR] An error occurred while running subprocess native-run.

        native-run.cmd android --app
        platforms\android\app\build\outputs\apk\debug\app-d... exited with exit
        code 1.

        Re-running this command with the --verbose flag may provide more
        information.




can somebody help me..
my app is build successfully but not run why

**Comment by Shehryar169** [comment] 2019-07-24 09:23
> BUILD SUCCESSFUL in 11s
> 42 actionable tasks: 42 up-to-date
> Built the following apk(s):
> D:\beauty_JH\bj\platforms\android\app\build\outputs\apk\debug\app-debug.
> apk
> 
> > native-run.cmd android --app platforms\android\app\build\outputs\apk\debug\app
> > -debug.apk
> > Error: Command failed: C:\Users\xamrin\AppData\Local\Android\Sdk\platform-tools
> > adb devices -l
> 
> ```
> at ChildProcess.exithandler (child_process.js:294:12)
> at ChildProcess.emit (events.js:198:13)
> at maybeClose (internal/child_process.js:982:16)
> at Socket.stream.socket.on (internal/child_process.js:389:11)
> at Socket.emit (events.js:198:13)
> at Pipe._handle.close (net.js:606:12)
> ```
> 
> [ERROR] An error occurred while running subprocess native-run.
> 
> ```
>     native-run.cmd android --app
>     platforms\android\app\build\outputs\apk\debug\app-d... exited with exit
>     code 1.
> 
>     Re-running this command with the --verbose flag may provide more
>     information.
> ```
> 
> can somebody help me..
> my app is build successfully but not run why

Same Issue. Please help

**Comment by dwieeb** [comment] 2019-07-24 16:46
@XamrinIndian @Shehryar169 Can one of you fill out a new issue? That's unrelated to the original issue.
