### ISSUE TITLE
I can't run basic tabs app  on my device. Error: connect ECONNREFUSED 127.0.0.1:27015   

### ISSUE THREAD

**Issue by davazro** [ionic-team/native-run#113] opened 2020-04-04 15:16 UTC
**Version:**

`1.0.0`

**Description:**
I can't run basic tabs app  on my device. I get this Error: connect ECONNREFUSED 127.0.0.1:27015   
I've got my Xiaomi redmi note 7 connected with activated developer mode, debug mode, allow install from usb, etc.  I also deactivated antivirus firewall on my pc.

What's the problem?

Can anyone help me?

**Command Output:**

```
PS D:\dav_mis_doc\cursos\Ionic 5 Udemy\3_10_tabs\myApp> native-run --list --verbose
  client:usbmuxd connectUsbmuxdSocket +0ms
  client:usbmuxd getDevices +24ms
  protocol:usbmux socket write: {"messageType":"ListDevices"} +0ms
  native-run:android:utils:sdk:resolveSDKRoot Looking for $ANDROID_HOME +0ms
  native-run:android:utils:sdk:resolveSDKRoot Looking for $ANDROID_SDK_ROOT +10ms
  native-run:android:utils:sdk:resolveSDKRoot Looking at following directories: [ 'C:\\Users\\Usuario\\AppData\\Local\\Android\\Sdk' ] +0ms
  native-run:android:utils:sdk:resolveSDKRoot Using C:\Users\Usuario\AppData\Local\Android\Sdk +33ms
  native-run:android:utils:sdk:resolveEmulatorHome Looking for $ANDROID_EMULATOR_HOME +0ms
  native-run:android:utils:sdk:resolveEmulatorHome Looking at $HOME/.android +0ms
  native-run:android:utils:sdk:resolveEmulatorHome Using $HOME/.android/ at C:\Users\Usuario\.android +2ms       
  native-run:android:utils:sdk:resolveAVDHome Looking for $ANDROID_AVD_HOME +0ms
  native-run:android:utils:sdk:resolveAVDHome Looking at $HOME/.android/avd +1ms
  native-run:android:utils:sdk:resolveAVDHome Using $HOME/.android/avd/ at C:\Users\Usuario\.android\avd +1ms    
  native-run:android:utils:sdk:getSDKPackage Parsing C:\Users\Usuario\AppData\Local\Android\Sdk\platform-tools\package.xml +0ms
  native-run:android:utils:avd:getAVDINIs Discovered AVD ini files: [ 'C:\\Users\\Usuario\\.android\\avd\\Nexus_4_API_22.ini',
  native-run:android:utils:avd:getAVDINIs   'C:\\Users\\Usuario\\.android\\avd\\Nexus_5_API_26.ini' ] +0ms       
  native-run:android:utils:adb:getDevices Invoking adb: 'C:\\Users\\Usuario\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb' [ 'devices', '-l' ] +0ms
  native-run:android:utils:sdk:findAllSDKPackages Walking C:\Users\Usuario\AppData\Local\Android\Sdk to discover 
SDK packages +0ms
  native-run:android:utils:adb:parseAdbDevices Parsing adb devices from output lines: [ 'List of devices attached',
  native-run:android:utils:adb:parseAdbDevices   '407ccc9a               device product:lavender_eea model:Redmi_Note_7 device:lavender transport_id:14',
  native-run:android:utils:adb:parseAdbDevices   '',
  native-run:android:utils:adb:parseAdbDevices   '' ] +0ms
  native-run:android:utils:adb:getDeviceProperties Invoking adb: 'C:\\Users\\Usuario\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb' [ '-s', '407ccc9a', 'shell', 'getprop' ] +0ms
  native-run:android:utils:adb:getDevices Found adb devices: [ { serial: '407ccc9a',
  native-run:android:utils:adb:getDevices     state: 'device',
  native-run:android:utils:adb:getDevices     type: 'hardware',
  native-run:android:utils:adb:getDevices     connection: null,
  native-run:android:utils:adb:getDevices     properties:
  native-run:android:utils:adb:getDevices      { product: 'lavender_eea',
  native-run:android:utils:adb:getDevices        model: 'Redmi_Note_7',
  native-run:android:utils:adb:getDevices        device: 'lavender',
  native-run:android:utils:adb:getDevices        transport_id: '14' },
  native-run:android:utils:adb:getDevices     manufacturer: 'Xiaomi',
  native-run:android:utils:adb:getDevices     model: 'Redmi Note 7',
  native-run:android:utils:adb:getDevices     product: 'lavender_eea',
  native-run:android:utils:adb:getDevices     sdkVersion: '28' } ] +409ms
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:27015
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1104:14)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**SDK Info:**

```
SDK Location:         C:\Users\Usuario\AppData\Local\Android\Sdk
AVD Home:             C:\Users\Usuario\.android\avd

API Level:            29
Packages:             Android SDK Platform 29  platforms;android-29  4
                      Sources for Android 29  sources;android-29  1
(!) Missing Packages: Google Play Intel x86 Atom System Image  system-images;android-29;google_apis_playstore;x86  /.+/


API Level:            28
Packages:             Android SDK Platform 28  platforms;android-28  6
                      Sources for Android 28  sources;android-28  1
(!) Missing Packages: Google Play Intel x86 Atom System Image  system-images;android-28;google_apis_playstore;x86  /.+/


API Level:            27
Packages:             Android SDK Platform 27  platforms;android-27  3
(!) Missing Packages: Google Play Intel x86 Atom System Image  system-images;android-27;google_apis_playstore;x86  /.+/


API Level:            25
Packages:             Android SDK Platform 25  platforms;android-25  3
(!) Missing Packages: Google Play Intel x86 Atom System Image  system-images;android-25;google_apis_playstore;x86  /.+/


Tools:

Android Emulator  emulator  30.0.5
Android SDK Build-Tools 28.0.3  build-tools;28.0.3  28.0.3
Android SDK Build-Tools 29.0.3  build-tools;29.0.3  29.0.3
Android SDK Platform-Tools  platform-tools  29.0.6
SDK Patch Applier v4  patcher;v4  1
```

**Comment by dwieeb** [comment] 2020-04-04 19:46
Duplicate of https://github.com/ionic-team/native-run/issues/35

**Closed by dwieeb** 2020-04-04 19:46 UTC
Labels: android

**Comment by Maraoui21** [comment] 2023-01-14 19:23
same problem here any solutions ?
