### ISSUE TITLE
Error: InvalidService

### ISSUE THREAD

**Issue by cmeuser** [ionic-team/native-run#156] opened 2020-09-24 16:13 UTC
**Version:**

1.1.0

**Description:**

App does not launch on iOS device.

**Command Output:**

> native-run ios --app "platforms/ios/build/device/Lexis Plus.ipa" --device
[native-run] Error: InvalidService
[native-run]     at LockdownProtocolReader.parseBody (/usr/local/lib/node_modules/native-run/dist/ios/lib/protocol/lockdown.js:37:19)
[native-run]     at LockdownProtocolReader.onData (/usr/local/lib/node_modules/native-run/dist/ios/lib/protocol/protocol.js:53:40)
[native-run]     at TLSSocket.emit (events.js:310:20)
[native-run]     at addChunk (_stream_readable.js:286:12)
[native-run]     at readableAddChunk (_stream_readable.js:268:9)
[native-run]     at TLSSocket.Readable.push (_stream_readable.js:209:10)
[native-run]     at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
[ERROR] An error occurred while running subprocess native-run.

**Environment Info:**

Ionic:

   Ionic CLI                     : 6.11.8 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.2
   @angular-devkit/build-angular : 0.901.8
   @angular-devkit/schematics    : 9.1.8
   @angular/cli                  : 9.1.8
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0, ios 6.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 12 other plugins)

Utility:

   cordova-res : 0.15.1
   native-run  : 1.1.0

System:

   Android SDK Tools : 26.1.1 (/Users/meusercx/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 8.0.2
   NodeJS            : v12.16.2 (/usr/local/bin/node)
   npm               : 6.14.8
   OS                : macOS Catalina
   Xcode             : Xcode 12.0 Build version 12A7209

macOS version:

10.15.6

Xcode version:

12.0

**Comment by imhoffd** [comment] 2020-09-24 20:15
Duplicate of https://github.com/ionic-team/native-run/issues/60

**Closed as completed** 2020-09-24 20:15 UTC
Labels: ios
