### ISSUE TITLE
ERR_UNKNOWN: Path 'platforms/ios/build/emulator/myapp.app' not found

### ISSUE THREAD

**Issue by Borongaj** [ionic-team/native-run#41] opened 2019-06-07 15:42 UTC
ionic cordova prepare ios 
ionic cordova run ios -l --address=0.0.0.0 --verbose

### This is the ending log:

[cordova] 
[cordova] No scripts found for hook "after_compile".
[cordova] No scripts found for hook "after_build".
native-run ios --app platforms/ios/build/emulator/myapp.app --virtual --connect --forward 8100:8100 --verbose
[native-run] 2019-06-07T15:29:56.431Z native-run Caught fatal error: { Error: Path 'platforms/ios/build/emulator/myapp.app' not found
[native-run]     at Object.run (/usr/local/lib/node_modules/native-run/dist/ios/run.js:23:15)
[native-run]     at Object.run (/usr/local/lib/node_modules/native-run/dist/ios/index.js:14:15)
[native-run]     at process.runNextTicks [as _tickCallback] (internal/process/next_tick.js:47:5)
[native-run]     at Function.Module.runMain (internal/modules/cjs/loader.js:800:11)
[native-run]     at executeUserCode (internal/bootstrap/node.js:526:15)
[native-run]     at startMainThreadExecution (internal/bootstrap/node.js:439:3) code: undefined, exitCode: 1, data: undefined }
[native-run] ERR_UNKNOWN: Path 'platforms/ios/build/emulator/myapp.app' not found
[ERROR] An error occurred while running subprocess native-run.
native-run ios --app platforms/ios/build/emulator/myapp.app --virtual --conne... exited with exit code 1.
 Re-running this command with the --verbose flag may provide more information.
  ionic:utils-process onBeforeExit handler: 'process.exit' received +0ms
  ionic:utils-process onBeforeExit handler: running 5 functions +0ms
  ionic:lib:hooks Looking for ionic:serve:after npm script. +35s
  ionic:utils-process processExit: exiting (exit code: 1) +135ms

**Comment by dwieeb** [comment] 2019-06-07 15:49
@Borongaj What is the output just before that? Where is Cordova putting the `.app` binary?

**Comment by Borongaj** [comment] 2019-06-07 17:03
### Log before :

[cordova] Preparing Firebase on iOS
[cordova] No scripts found for hook "before_compile".
[cordova] Building for iPhone Xʀ Simulator
[cordova] Building project: /Users/laurentgleizes/Documents/DEV/Ionic/myapp/platforms/ios/myapp.xcworkspace
[cordova]       Configuration: Debug
[cordova]       Platform: emulator
[cordova] Build settings from command line:
[cordova]     CONFIGURATION_BUILD_DIR = /Users/laurentgleizes/Documents/DEV/Ionic/myapp/platforms/ios/build/emulator
[cordova]     SDKROOT = iphonesimulator12.2
[cordova]     SHARED_PRECOMPS_DIR = /Users/laurentgleizes/Documents/DEV/Ionic/myapp/platforms/ios/build/sharedpch
[cordova] 
[cordova] Build settings from configuration file '/Users/laurentgleizes/Documents/DEV/Ionic/myapp/platforms/ios/cordova/build-debug.xcconfig':
[cordova]     CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES
[cordova]     CODE_SIGN_ENTITLEMENTS = $(PROJECT_DIR)/$(PROJECT_NAME)/Entitlements-$(CONFIGURATION).plist
[cordova]     CODE_SIGN_IDENTITY = iPhone Developer
[cordova]     ENABLE_BITCODE = NO
[cordova]     FRAMEWORK_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/GoogleMaps/Base/Frameworks" "${PODS_ROOT}/GoogleMaps/Maps/Frameworks"
[cordova]     GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
[cordova]     HEADER_SEARCH_PATHS = "$(TARGET_BUILD_DIR)/usr/local/lib/include" "$(OBJROOT)/UninstalledProducts/include" "$(OBJROOT)/UninstalledProducts/$(PLATFORM_NAME)/include" "$(BUILT_PRODUCTS_DIR)"
[cordova]     OTHER_LDFLAGS = $(inherited) -ObjC -l"c++" -l"z" -framework "Accelerate" -framework "CoreData" -framework "CoreGraphics" -framework "CoreImage" -framework "CoreLocation" -framework "CoreTelephony" -framework "CoreText" -framework "GLKit" -framework "GoogleMaps" -framework "GoogleMapsBase" -framework "GoogleMapsCore" -framework "ImageIO" -framework "OpenGLES" -framework "QuartzCore" -framework "SystemConfiguration" -framework "UIKit"
[cordova]     PODS_BUILD_DIR = ${BUILD_DIR}
[cordova]     PODS_CONFIGURATION_BUILD_DIR = ${PODS_BUILD_DIR}/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
[cordova]     PODS_PODFILE_DIR_PATH = ${SRCROOT}/.
[cordova]     PODS_ROOT = ${SRCROOT}/Pods
[cordova]     SWIFT_OBJC_BRIDGING_HEADER = $(PROJECT_DIR)/$(PROJECT_NAME)/Bridging-Header.h

### myapp.app path

/Users/laurentgleizes/Library/Developer/Xcode/DerivedData/myapp-bwkvzmhxgfgunvbrealhmvnemzsf/Build/Products/Debug-iphonesimulator/myapp.app

**Comment by dwieeb** [comment] 2019-06-07 19:16
The path you provided is where Xcode puts the binary, not Cordova.

Look in `./platforms/ios/build/emulator`. I am just trying to discover why the binary isn't where it's supposed to be.

**Comment by dwieeb** [comment] 2019-06-07 19:18
Could you also provide the output of `ionic info`?

**Comment by Borongaj** [comment] 2019-06-07 20:02
Seems related to Xcode New Build System ('Modern' one). 

I solved the problem adding this file inside my project root folder :

**Filename** : build.json

**Content** :

{
 "ios": {
    "debug": {
      "buildFlag": [
        "-UseModernBuildSystem=0"
      ],
      "developmentTeam": "YOUR_DEV_TEAM_ID"
    },
    "release": {
      "buildFlag": [
        "-UseModernBuildSystem=0"
      ],
      "developmentTeam": "YOUR_DEV_TEAM_ID"
    }
  }
}

**Comment by theHellyar** [comment] 2019-06-23 04:57
@Borongaj - Worked for me! thanks!

**Comment by tlancina** [comment] 2019-06-24 22:07
@Borongaj @theHellyar would you guys be able to post `ionic info` if you get a chance? Trying to reproduce what could cause this to happen (since clearly from https://github.com/ionic-team/native-run/issues/41#issuecomment-499962773 `CONFIGURATION_BUILD_DIR` is `myapp/platforms/ios/build/emulator`). Not sure if it's related to Xcode, Cordova or something else at this point, since I'm unable to repro.

Thanks!

**Comment by theHellyar** [comment] 2019-06-24 22:09
@tlancina 

Ionic:

   Ionic CLI          : 5.1.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.2

Cordova:

   Cordova CLI       : 8.0.0
   Cordova Platforms : android 7.0.0, ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.0, (and 4 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.6 

System:

   Android SDK Tools : 26.1.1 (/Users/bch/Library/Android/sdk)
   ios-deploy        : 2.0.0
   NodeJS            : v10.15.3 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.2 Build version 10E125

**Comment by tlancina** [comment] 2019-06-24 23:50
@theHellyar thank you! I'm going to close this as it looks like it's from the lack of Xcode 10 support in cordova-ios 4 (this particular error happening because the cordova build stops abruptly and native-run tries to run the `.app` which should have been produced).

For anyone running in to this error in the future using cordova-ios 4 and Xcode 10+, you can either use the `useModernBuildSystem=0` flag from https://github.com/apache/cordova-ios/issues/407#issue-360392411 as @Borongaj correctly pointed out, or upgrade to `cordova-ios` 5.

**Closed by tlancina** 2019-06-24 23:50 UTC
Labels: ios

**Comment by rolinger** [comment] 2019-08-29 16:38
@Borongaj @theHellyar 

Hey all, I upgraded from cli v1.7.14 to 5.2.6 for use with my Ionic-v1 app.  Everything deploys just fine on Android....but lots of problems on iOS

One of which is when I build the app it exits with no errors or issues, but it fails to build the `platforms/ios/build` directory, which in turn causes the `ionic cordova run ios --device` to fail.  Looking closer and other other peoples similar posts, I see my `build` simply just cleanly exits as `Preparing Firebase on iOS` - no error messages or anything...I think this is why its not intially creating the build folder, but I have no idea what to do or look at.  Same results with or without the `UserModernBuildSystem` flag:

```
/users/macknife/dev/MyApp> ionic cordova build ios --buildFlag='-UserModernBuildSystem=0' --verbose
  ionic:lib Terminal info: { ci: false, shell: '/bin/bash', tty: true, windows: false } +0ms
  ionic:lib CLI global options: { _: [ 'cordova', 'build', 'ios' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, buildFlag: '-UserModernBuildSystem=0', project: null, '--': [] } +5ms
  ionic:lib:project Project type from config: Ionic 1 (ionic1) +0ms
  ionic:lib:project Project details: { configPath: '/Users/macknife/dev/MyApp/ionic.config.json', errors: [], context: 'app', type: 'ionic1' } +0ms
  ionic Context: { binPath: '/usr/local/lib/node_modules/ionic/bin/ionic', libPath: '/usr/local/lib/node_modules/ionic', execPath: '/Users/macknife/dev/MyApp', version: '5.2.6' } +0ms
  ionic:lib:integrations:cordova:config Loading Cordova Config (config.xml: '/Users/macknife/dev/MyApp/config.xml', package.json: '/Users/macknife/dev/MyApp/package.json') +0ms
  ionic:lib:build build options: { '--': [],
  ionic:lib:build   engine: 'cordova',
  ionic:lib:build   platform: 'ios',
  ionic:lib:build   project: undefined,
  ionic:lib:build   verbose: false,
  ionic:lib:build   type: 'ionic1' } +0ms
  ionic:lib:telemetry Sending telemetry for command: 'ionic cordova build' [ 'ios',
  ionic:lib:telemetry   '--verbose',
  ionic:lib:telemetry   '--interactive',
  ionic:lib:telemetry   '--color',
  ionic:lib:telemetry   '--build-flag=-UserModernBuildSystem=0' ] +0ms
  ionic:lib:hooks Looking for ionic:build:before npm script. +0ms
  ionic:lib:build Looking for ionic:build npm script. +12ms
> ionic-v1 build
  ionic:v1-toolkit:lib:gulp Using gulpfile: /Users/macknife/dev/MyApp/gulpfile.js +0ms
  ionic:v1-toolkit:lib:gulp Using gulp: /Users/macknife/dev/MyApp/node_modules/gulp/index.js +2ms
  ionic:v1-toolkit:lib:gulp Loaded gulp tasks: { default: { fn: [Function], dep: [ 'sass' ], name: 'default' }, sass: { fn: [Function], dep: [], name: 'sass' }, watch: { fn: [Function], dep: [ 'sass' ], name: 'watch' } } +957ms
[10:25:49] Invoking sass gulp task.
  ionic:lib:hooks Looking for ionic:build:after npm script. +3s
> cordova build ios --verbose
No scripts found for hook "before_build".
Executing script found in plugin cordova-custom-config for hook "before_prepare": plugins/cordova-custom-config/hooks/restoreBackups.js
cordova-custom-config: Loaded module dependencies
cordova-custom-config: Running restoreBackups.js
cordova-custom-config: Skipping auto-restore of config file backup(s)
Executing script found in plugin cordova-custom-config for hook "before_prepare": plugins/cordova-custom-config/hooks/applyCustomConfig.js
cordova-custom-config: Loaded module dependencies
cordova-custom-config: Running applyCustomConfig.js
cordova-custom-config: Finished applying platform config
Checking config.xml and package.json for saved platforms that haven't been added to the project
Config.xml and package.json platforms are the same. No pkg.json modification.
Package.json and config.xml platforms are different. Updating config.xml with most current list of platforms.
PlatformApi successfully found for platform ios
Checking for saved plugins that haven't been added to the project
Checking for any plugins added to the project that have not been installed in ios platform
No differences found between plugins added to project and installed in ios platform. Continuing...
Generating platform-specific config.xml from defaults for iOS at /users/macknife/dev/MyApp/platforms/ios/MyApp/config.xml
Merging project's config.xml into platform-specific iOS config.xml
Merging and updating files from [www, platforms/ios/platform_www] to platforms/ios/www
  copy  www/css/ionic.app.css platforms/ios/www/css/ionic.app.css (updated file)
  copy  www/css/ionic.app.min.css platforms/ios/www/css/ionic.app.min.css (updated file)
  copy  www/index.html platforms/ios/www/index.html (updated file)
Current launch storyboard CDVLaunchScreen
Not changing launch storyboard setting in info plist.
Wrote out iOS Bundle Version "0.2.90" to /users/macknife/dev/MyApp/platforms/ios/MyApp/MyApp-Info.plist
No need to update build settings for launch storyboard support.
Set IPHONEOS_DEPLOYMENT_TARGET to "9.3".
Did not update build settings for launch storyboard support.
iOS Product Name has not changed (still "MyApp")
Updating icons at platforms/ios/MyApp/Images.xcassets/AppIcon.appiconset/
Updating splash screens at platforms/ios/MyApp/Images.xcassets/LaunchImage.launchimage/
Updating launch storyboard images at platforms/ios/MyApp/Images.xcassets/LaunchStoryboard.imageset/
Updating Storyboard image set contents.json
This app does not have additional resource files defined
Prepared iOS project successfully
Executing script found in hooks directory for hook "after_prepare": hooks/after_prepare/010_add_platform_class.js
Running command: /users/macknife/dev/MyApp/hooks/after_prepare/010_add_platform_class.js /users/macknife/dev/MyApp
add to body class: platform-ios
Command finished with error code 0: /users/macknife/dev/MyApp/hooks/after_prepare/010_add_platform_class.js /users/macknife/dev/MyApp
Executing script found in plugin cordova-custom-config for hook "after_prepare": plugins/cordova-custom-config/hooks/applyCustomConfig.js
cordova-custom-config: Loaded module dependencies
cordova-custom-config: Running applyCustomConfig.js
cordova-custom-config: Finished applying platform config
Executing script found in plugin cordova-plugin-facebook4 for hook "after_prepare": plugins/cordova-plugin-facebook4/scripts/after_prepare.js
Executing script found in plugin cordova-plugin-firebasex for hook "after_prepare": plugins/cordova-plugin-firebasex/scripts/after_prepare.js
Preparing Firebase on iOS
```

My env:
```
Ionic:

   Ionic CLI         : 5.2.6 (/usr/local/lib/node_modules/ionic)
   Ionic Framework   : ionic1 1.0.0
   @ionic/v1-toolkit : 1.0.22

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, (and 32 other plugins)

Utility:

   cordova-res : 0.6.0 
   native-run  : 0.2.8 

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v10.16.3 (/usr/local/bin/node)
   npm        : 6.11.2
   OS         : macOS High Sierra
   Xcode      : Xcode 10.1 Build version 10B61
```

**Comment by rolinger** [comment] 2019-08-29 21:26
Well, nix that...issue was related to Cordova-plugin-firebasex v6.0.7, I downgraded it v6.0.6 and things are now working.  Was driving me nuts though.

**Comment by junaid5546** [comment] 2020-01-06 09:44
This worked for me:
1- ionic cordova platform rm ios
2-ionic cordova platform add ios
3- ionic cordova run ios -l

**Comment by ramakrishna-src** [comment] 2020-01-13 10:22
when i run this command in visual studio code **ionic cordova  emulate ios** i got this error

**./platforms/ios/build** --build folder is not created in my project 
and i am new to ios app
![Screen Shot 2020-01-13 at 15 44 35](https://user-images.githubusercontent.com/58976856/72247880-dc85e200-361b-11ea-9c57-aecd20942da4.png)

**[native-run] ERR_UNKNOWN: Path 'platforms/ios/build/emulator/myapp.app' not found**
Thanks.

**Comment by tlancina** [comment] 2020-01-16 15:51
@ramakrishna-src I think I've seen that before, the Cordova build is stopping short so there's nothing for `native-run` to run.  Make sure your `cordova-ios` version is up to date and supports the latest version of Xcode (you can check it with `ionic info`)

**Comment by ramakrishna-src** [comment] 2020-01-23 12:18
Thank you @tlancina  my problem was fixed

**Comment by ramakrishna-src** [comment] 2020-01-23 12:19
Thank you @tlancina  my problem was fixed

**Comment by ramakrishna-src** [comment] 2020-01-23 12:35
Hi @tlancina i got white space issue b/w header and content whenever **drag the content up and down**  
**note**:only got this problem in ios app using ionic 3 and in android working fine please help me
![1579782639502](https://user-images.githubusercontent.com/58976856/72984903-c42b7980-3e0a-11ea-90bf-18fcc053e0d2.JPEG)
thanks

**Comment by ramakrishna-src** [comment] 2020-01-23 12:38
i did this but scrolling is not smooth
.ios {
  <your-screen> {
    .scroll-content {
      -webkit-overflow-scrolling: auto !important;
    }
  }
}
