### ISSUE TITLE
RangeError [ERR_OUT_OF_RANGE]

### ISSUE THREAD

**Issue by meuser** [ionic-team/native-run#137] opened 2020-07-18 15:02 UTC
Unable to run native-run on iOS with Ionic projects with ™ in the config name tag.  Android runs fine.  Note that there is no problem running the app directly from xcode.

> native-run ios --app platforms/ios/build/device/MyApp™.ipa --device
[native-run] RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 26. Received 27
[native-run]     at boundsError (internal/buffer.js:77:9)
[native-run]     at writeU_Int8 (internal/buffer.js:732:5)
[native-run]     at Buffer.writeUInt8 (internal/buffer.js:739:10)
[native-run]     at toCString (/usr/local/lib/node_modules/native-run/node_modules/node-ioslib/dist/client/afc.js:150:9)
[native-run]     at AFCClient.makeDirectory (/usr/local/lib/node_modules/native-run/node_modules/node-ioslib/dist/client/afc.js:84:19)
[native-run]     at AFCClient.uploadDirectory (/usr/local/lib/node_modules/native-run/node_modules/node-ioslib/dist/client/afc.js:89:20)
[native-run]     at uploadApp (/usr/local/lib/node_modules/native-run/dist/ios/utils/device.js:85:21)
[native-run]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[native-run]     at async Object.runOnDevice (/usr/local/lib/node_modules/native-run/dist/ios/utils/device.js:31:9)
[native-run]     at async Object.run (/usr/local/lib/node_modules/native-run/dist/ios/run.js:52:13)
[ERROR] An error occurred while running subprocess native-run.
        
        native-run ios --app platforms/ios/build/device/MyApp™.ipa --device exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.

**Comment by imhoffd** [comment] 2020-07-20 23:25
Duplicate of https://github.com/ionic-team/native-run/issues/65

**Closed as completed by imhoffd** 2020-07-20 23:25 UTC
