### ISSUE TITLE
No hardware devices found

### ISSUE THREAD

**Issue by coloz** [ionic-team/native-run#54] opened 2019-06-23 11:38 UTC
**Version:**
0.2.6

**Description:**
The device could not be found，but using **ionic cordova run android** is all right.

**Command Output:**
```
2019-06-23T11:21:14.880Z native-run:android:utils:adb:getDeviceProperties Invoking adb: 'C:\\Users\\clz\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb' [ '-s', '573154575a563398', 'shell', 'getprop' ]
2019-06-23T11:21:15.060Z native-run:android:utils:adb:getDevices Found adb devices: [ { serial: '573154575a563398',
    state: 'device',
    type: 'emulator',
    connection: null,
    properties:
     { product: 'starqltezc',
       model: 'SM_G9600',
       device: 'starqltechn',
       transport_id: '2' },
    manufacturer: 'samsung',
    model: 'SM-G9600',
    product: 'starqltezc',
    sdkVersion: '28' } ]
2019-06-23T11:21:15.061Z native-run:android:utils:avd:getAVDINIs Discovered AVD ini files: [ 'C:\\Users\\clz\\.android\\avd\\Nexus_5X_API_23.ini',
  'C:\\Users\\clz\\.android\\avd\\Nexus_5X_API_28_x86.ini',
  'C:\\Users\\clz\\.android\\avd\\Nexus_5_API_22.ini',
  'C:\\Users\\clz\\.android\\avd\\Pixel_2_API_27.ini',
  'C:\\Users\\clz\\.android\\avd\\Pixel_2_API_28.ini',
  'C:\\Users\\clz\\.android\\avd\\Pixel_2_XL_API_26.ini' ]
2019-06-23T11:21:15.068Z native-run Caught fatal error: { Error: No hardware devices found. Not attempting emulator because --device was specified.
    at selectDevice (C:\Users\clz\AppData\Roaming\npm\node_modules\native-run\dist\android\run.js:82:19) code: 'ERR_NO_DEVICE', exitCode: 1, data: undefined }
ERR_NO_DEVICE: No hardware devices found. Not attempting emulator because --device was specified.
```

**SDK Info:**
```
Ionic:

   Ionic CLI                     : 5.1.0 (C:\Users\clz\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.3.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 7.1.4
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 33 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.6

System:

   NodeJS : v10.15.1 (D:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by dwieeb** [comment] 2019-06-24 14:17
@coloz What is the output of `adb devices -l` ?

**Comment by coloz** [comment] 2019-06-25 01:16
> @coloz What is the output of `adb devices -l` ?

List of devices attached
573154575a563398       device product:starqltezc model:SM_G9600 device:starqltechn transport_id:1

**Comment by coloz** [comment] 2019-06-25 01:26
i use vscode cordova tools.
I found that when I chose **Run Android on emulator**, it would install APK on my real mobile phone and prompt me that the emulator could not be found.

**Comment by dwieeb** [comment] 2019-06-25 21:25
@coloz Thanks. From the information given with `adb devices -l`, I can confidently say this is a duplicate of https://github.com/ionic-team/native-run/issues/42. I am making a release right now to address this issue.

**Closed by dwieeb** 2019-06-25 21:25 UTC
Labels: android
