### ISSUE TITLE
--list causes unhandled error

### ISSUE THREAD

**Issue by andrewzagorski** [ionic-team/native-run#106] opened 2020-02-02 02:01 UTC
I want to start by saying this almost certainly is not unique and I'm just stupid but I can't find a fix, if someone could point me to one I would be very happy.

**Version:**

0.3.0

**Description:**

native-run --list causes an unhandled 'error' event
native-run android --app gives ERR_BAD_INPUT: --app is required

**Command Output:**
native-run android --app --verbose makes the command work and runs the app on an emulator

λ native-run --list --verbose
  client:usbmuxd connectUsbmuxdSocket +0ms
  client:usbmuxd getDevices +16ms
  protocol:usbmux socket write: {"messageType":"ListDevices"} +0ms
  native-run:android:utils:sdk:resolveSDKRoot Looking for $ANDROID_HOME +0ms
  native-run:android:utils:sdk:resolveSDKRoot Looking for $ANDROID_SDK_ROOT +1ms
  native-run:android:utils:sdk:resolveSDKRoot Looking at following directories: [ 'C:\\Users\\orang\\AppData\\Local\\Android\\Sdk' ] +1ms
  native-run:android:utils:sdk:resolveSDKRoot Using C:\Users\orang\AppData\Local\Android\Sdk +6ms
  native-run:android:utils:sdk:resolveEmulatorHome Looking for $ANDROID_EMULATOR_HOME +0ms
  native-run:android:utils:sdk:resolveEmulatorHome Looking at $HOME/.android +1ms
  native-run:android:utils:sdk:resolveEmulatorHome Using $HOME/.android/ at C:\Users\orang\.android +1ms
  native-run:android:utils:sdk:resolveAVDHome Looking for $ANDROID_AVD_HOME +0ms
  native-run:android:utils:sdk:resolveAVDHome Looking at $HOME/.android/avd +0ms
  native-run:android:utils:sdk:resolveAVDHome Using $HOME/.android/avd/ at C:\Users\orang\.android\avd +1ms
  native-run:android:utils:sdk:getSDKPackage Parsing C:\Users\orang\AppData\Local\Android\Sdk\platform-tools\package.xml +0ms
  native-run:android:utils:avd:getAVDINIs Discovered AVD ini files: [ 'C:\\Users\\orang\\.android\\avd\\Pixel_2_API_29.ini',
  native-run:android:utils:avd:getAVDINIs   'C:\\Users\\orang\\.android\\avd\\Pixel_3_API_29.ini' ] +0ms
  native-run:android:utils:adb:getDevices Invoking adb: 'C:\\Users\\orang\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb' [ 'devices', '-l' ] +0ms
  native-run:android:utils:sdk:findAllSDKPackages Walking C:\Users\orang\AppData\Local\Android\Sdk to discover SDK packages +0ms
  native-run:android:utils:adb:parseAdbDevices Parsing adb devices from output lines: [ 'List of devices attached', '', '' ] +0ms
  native-run:android:utils:adb:getDevices Found adb devices: [] +64ms
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:27015
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**SDK Info:**

SDK Location:         C:\Users\orang\AppData\Local\Android\Sdk
AVD Home:             C:\Users\orang\.android\avd

API Level:            29
Packages:             Android SDK Platform 29  platforms;android-29  4
                      Google Play Intel x86 Atom System Image  system-images;android-29;google_apis_playstore;x86  8
                      Sources for Android 29  sources;android-29  1

API Level:            28
Packages:             Android SDK Platform 28  platforms;android-28  6
                      Sources for Android 28  sources;android-28  1
(!) Missing Packages: Google Play Intel x86 Atom System Image  system-images;android-28;google_apis_playstore;x86  /.+/

Tools:

Android Emulator  emulator  29.3.4
Android SDK Build-Tools 29.0.3  build-tools;29.0.3  29.0.3
Android SDK Platform-Tools  platform-tools  29.0.5
Android SDK Tools  tools  26.1.1
SDK Patch Applier v4  patcher;v4  1

**Comment by dwieeb** [comment] 2020-02-02 22:14
@andrewzagorski Thanks for the issue report! I believe this is a duplicate of https://github.com/ionic-team/native-run/issues/35

The workaround is `native-run android --list`.

**Closed** 2020-04-04 19:46 UTC
Labels: android
