### ISSUE TITLE
Error: Command failed: adb -s emulator-5554 shell getprop

### ISSUE THREAD

**Issue by mimzo-solutions** [ionic-team/native-run#43] opened 2019-06-10 01:26 UTC
Ionic:

   Ionic CLI                     : 5.0.1 (C:\Users\admin\AppData\Roaming\npm\nod
e_modules\ionic)
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic
-webview 4.0.1, (and 9 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.4

System:

   Android SDK Tools : 26.1.1 (C:\Users\admin\AppData\Local\Android\Sdk)
   NodeJS            : v8.11.4 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 7

> native-run.cmd android --app platforms\android\app\build\outputs\apk\debug\app
-debug.apk --verbose
2019-06-10T01:11:47.271Z native-run:android:utils:sdk:resolveSDKRoot Looking for
 $ANDROID_HOME
2019-06-10T01:11:47.274Z native-run:android:utils:sdk:resolveSDKRoot Using $ANDR
OID_HOME at C:\Users\admin\AppData\Local\Android\Sdk
2019-06-10T01:11:47.275Z native-run:android:utils:sdk:resolveEmulatorHome Lookin
g for $ANDROID_EMULATOR_HOME
2019-06-10T01:11:47.275Z native-run:android:utils:sdk:resolveEmulatorHome Using
$HOME/.android/ at C:\Users\admin\.android
2019-06-10T01:11:47.275Z native-run:android:utils:sdk:resolveAVDHome Looking for
 $ANDROID_AVD_HOME
2019-06-10T01:11:47.275Z native-run:android:utils:sdk:resolveAVDHome Using $ANDR
OID_AVD_HOME at undefined
2019-06-10T01:11:47.276Z native-run:android:utils:sdk:getSDKPackage Parsing C:\U
sers\admin\AppData\Local\Android\Sdk\platform-tools\package.xml
2019-06-10T01:11:47.297Z native-run:android:utils:adb:getDevices Invoking adb: '
C:\\Users\\admin\\AppData\\Local\\Android\\Sdk\\platform-tools/adb' [ 'devices',
 '-l' ]
2019-06-10T01:11:47.323Z native-run:android:utils:adb:parseAdbDevices Parsing ad
b devices from output lines: [ 'List of devices attached',
  'emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_
for_x86 device:generic_x86 transport_id:2',
  '',
  '' ]
2019-06-10T01:11:47.324Z native-run:android:utils:adb:getDeviceProperties Invoki
ng adb: 'C:\\Users\\admin\\AppData\\Local\\Android\\Sdk\\platform-tools/adb' [ '
-s', 'emulator-5554', 'shell', 'getprop' ]
2019-06-10T01:11:47.373Z native-run Caught fatal error: { Error: Command failed:
 C:\Users\admin\AppData\Local\Android\Sdk\platform-tools/adb -s emulator-5554 sh
ell getprop

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 3221226356,
  signal: null,
  cmd: 'C:\\Users\\admin\\AppData\\Local\\Android\\Sdk\\platform-tools/adb -s em
ulator-5554 shell getprop',
  stdout: '[dalvik.vm.appimageformat]: [lz4]\r\n[dalvik.vm.dex2oat-Xms]: [64m]\r
\n[dalvik.vm.dex2oat-Xmx]: [512m]\r\n[dalvik.vm.dex2oat-minidebuginfo]: [true]\r
\n[dalvik.vm.dexopt.secondary]: [true]\r\n[dalvik.vm.heapsize]: [384m]\r\n[dalvi
k.vm.image-dex2oat-Xms]: [64m]\r\n[dalvik.vm.image-dex2oat-Xmx]: [64m]\r\n[dalvi
k.vm.isa.x86.features]: [default]\r\n[dalvik.vm.isa.x86.variant]: [x86]\r\n[dalv
ik.vm.lockprof.threshold]: [500]\r\n[dalvik.vm.stack-trace-dir]: [/data/anr]\r\n
[dalvik.vm.usejit]: [true]\r\n[dalvik.vm.usejitprofiles]: [true]\r\n[debug.atrac
e.tags.enableflags]: [0]\r\n[debug.force_rtl]: [0]\r\n[debug.hwui.renderer]: [sk
iagl]\r\n[dev.bootcomplete]: [1]\r\n[drm.service.enabled]: [true]\r\n[gsm.curren
t.phone-type]: [1]\r\n[gsm.defaultpdpcontext.active]: [true]\r\n[gsm.network.typ
e]: [LTE]\r\n[gsm.operator.alpha]: [Android]\r\n[gsm.operator.iso-country]: [us]
\r\n[gsm.operator.isroaming]: [false]\r\n[gsm.operator.numeric]: [310260]\r\n[gs
m.sim.operator.alpha]: [T-Mobile]\r\n[gsm.sim.operator.iso-country]: [us]\r\n[gs
m.sim.operator.numeric]: [310260]\r\n[gsm.sim.state]: [LOADED]\r\n[gsm.version.b
aseband]: [1.0.0.0]\r\n[gsm.version.ril-impl]: [android reference-ril 1.0]\r\n[h
wservicemanager.ready]: [true]\r\n[init.svc.adbd]: [running]\r\n[init.svc.audios
erver]: [running]\r\n[init.svc.bootanim]: [stopped]\r\n[init.svc.broadcastradio-
hal]: [running]\r\n[init.svc.cameraserver]: [running]\r\n[init.svc.console]: [ru
nning]\r\n[init.svc.dhcpclient_rtr]: [running]\r\n[init.svc.dhcpserver]: [runnin
g]\r\n[init.svc.drm]: [running]\r\n[init.svc.emu_hostapd]: [running]\r\n[init.sv
c.gatekeeperd]: [running]\r\n[init.svc.goldfish-logcat]: [running]\r\n[init.svc.
healthd]: [running]\r\n[init.svc.hidl_memory]: [running]\r\n[init.svc.hwservicem
anager]: [running]\r\n[init.svc.incidentd]: [running]\r\n[init.svc.installd]: [r
unning]\r\n[init.svc.ipv6proxy]: [running]\r\n[init.svc.keystore]: [running]\r\n
[init.svc.lmkd]: [running]\r\n[init.svc.logd]: [running]\r\n[init.svc.logd-reini
t]: [stopped]\r\n[init.svc.mdnsd]: [running]\r\n[init.svc.media]: [running]\r\n[
init.svc.mediadrm]: [running]\r\n[init.svc.mediaextractor]: [running]\r\n[init.s
vc.mediametrics]: [running]\r\n[init.svc.netd]: [running]\r\n[init.svc.netmgr]:
[running]\r\n[init.svc.perfprofd]: [running]\r\n[init.svc.qemu-props]: [running]
\r\n[init.svc.ranchu-net]: [stopped]\r\n[init.svc.ranchu-setup]: [stopped]\r\n[i
nit.svc.servicemanager]: [running]\r\n[init.svc.statsd]: [running]\r\n[init.svc.
storaged]: [running]\r\n[init.svc.surfaceflinger]: [running]\r\n[init.svc.therma
lservice]: [running]\r\n[init.svc.tombstoned]: [running]\r\n[init.svc.traced]: [
running]\r\n[init.svc.traced_probes]: [running]\r\n[init.svc.ueventd]: [running]
\r\n[init.svc.usbd]: [stopped]\r\n[init.svc.vndservicemanager]: [running]\r\n[in
it.svc.vold]: [running]\r\n[init.svc.wificond]: [running]\r\n[init.svc.wpa_suppl
icant]: [running]\r\n[init.svc.zygote]: [running]\r\n[keyguard.no_require_sim]:
[true]\r\n[log.tag.WifiHAL]: [D]\r\n[log.tag.stats_log]: [I]\r\n[logd.logpersist
d.enable]: [true]\r\n[media.mediadrmservice.enable]: [true]\r\n[net.bt.name]: [A
ndroid]\r\n[net.qtaguid_enabled]: [1]\r\n[net.tcp.default_init_rwnd]: [60]\r\n[p
ersist.sys.dalvik.vm.lib.2]: [libart.so]\r\n[persist.sys.gps.lpp]: [0]\r\n[persi
st.sys.timezone]: [GMT]\r\n[persist.sys.usb.config]: [adb]\r\n[persist.sys.webvi
ew.vmsize]: [141300560]\r\n[persist.traced.enable]: [1]\r\n[pm.dexopt.ab-ota]: [
speed-profile]\r\n[pm.dexopt.bg-dexopt]: [speed-profile]\r\n[pm.dexopt.boot]: [v
erify]\r\n[pm.dexopt.first-boot]: [quicken]\r\n[pm.dexopt.inactive]: [verify]\r\
n[pm.dexopt.install]: [speed-profile]\r\n[pm.dexopt.priv-apps-oob]: [false]\r\n[
pm.dexopt.priv-apps-oob-list]: [ALL]\r\n[pm.dexopt.shared]: [speed]\r\n[qemu.gle
s]: [1]\r\n[qemu.hw.mainkeys]: [0]\r\n[qemu.logcat]: [start]\r\n[qemu.sf.fake_ca
mera]: [front]\r\n[qemu.sf.lcd_density]: [420]\r\n[qemu.timezone]: [Unknown/Unkn
own]\r\n[ro.actionable_compatible_property.enabled]: [true]\r\n[ro.adb.secure]:
[0]\r\n[ro.allow.mock.location]: [0]\r\n[ro.art.hiddenapi.warning]: [1]\r\n[ro.b
aseband]: [unknown]\r\n[ro.bionic.ld.warning]: [1]\r\n[ro.board.platform]: []\r\
n[ro.boot.android_dt_dir]: [/sys/bus/platform/devices/ANDR0001:00/properties/and
roid/]\r\n[ro.boot.bootreason]: [reboot]\r\n[ro.boot.hardware]: [ranchu]\r\n[ro.
boot.serialno]: [EMULATOR29X0X11X0]\r\n[ro.boot.verifiedbootstate]: [orange]\r\n
[ro.boot.veritymode]: [enforcing]\r\n[ro.bootimage.build.date]: [Wed Apr 10 22:2
0:32 UTC 2019]\r\n[ro.bootimage.build.date.utc]: [1554934832]\r\n[ro.bootimage.b
uild.fingerprint]: [google/sdk_gphone_x86/generic_x86:9/PSR1.180720.093/5456446:
userdebug/dev-keys]\r\n[ro.bootloader]: [unknown]\r\n[ro.bootmode]: [unknown]\r\
n[ro.build.characteristics]: [emulator]\r\n[ro.build.date]: [Wed Apr 10 22:20:32
 UTC 2019]\r\n[ro.build.date.utc]: [1554934832]\r\n[ro.build.description]: [sdk_
gphone_x86-userdebug 9 PSR1.180720.093 5456446 dev-keys]\r\n[ro.build.display.id
]: [sdk_gphone_x86-userdebug 9 PSR1.180720.093 5456446 dev-keys]\r\n[ro.build.fi
ngerprint]: [google/sdk_gphone_x86/generic_x86:9/PSR1.180720.093/5456446:userdeb
ug/dev-keys]\r\n[ro.build.flavor]: [sdk_gphone_x86-userdebug]\r\n[ro.build.host]
: [wphl12.hot.corp.google.com]\r\n[ro.build.id]: [PSR1.180720.093]\r\n[ro.build.
product]: [generic_x86]\r\n[ro.build.system_root_image]: [true]\r\n[ro.build.tag
s]: [dev-keys]\r\n[ro.build.type]: [userdebug]\r\n[ro.build.user]: [android-buil
d]\r\n[ro.build.version.all_codenames]: [REL]\r\n[ro.build.version.base_os]: []\
r\n[ro.build.version.codename]: [REL]\r\n[ro.build.version.incremental]: [545644
6]\r\n[ro.build.version.min_supported_target_sdk]: [17]\r\n[ro.build.version.pre
view_sdk]: [0]\r\n[ro.build.version.release]: [9]\r\n[ro.build.version.sdk]: [28
]\r\n[ro.build.version.security_patch]: [2018-09-05]\r\n[ro.carrier]: [unknown]\
r\n[ro.com.android.dataroaming]: [true]\r\n[ro.com.google.locationfeatures]: [1]
\r\n[ro.config.alarm_alert]: [Alarm_Classic.ogg]\r\n[ro.config.nocheckin]: [yes]
\r\n[ro.config.notification_sound]: [pixiedust.ogg]\r\n[ro.config.ringtone]: [Ri
ng_Synth_04.ogg]\r\n[ro.control_privapp_permissions]: [disable]\r\n[ro.cp_system
_other_odex]: [0]\r\n[ro.crypto.fs_crypto_blkdev]: [/dev/block/dm-1]\r\n[ro.cryp
to.state]: [encrypted]\r\n[ro.crypto.type]: [block]\r\n[ro.dalvik.vm.native.brid
ge]: [0]\r\n[ro.debuggable]: [1]\r\n[ro.device_owner]: [false]\r\n[ro.hardware]:
 [ranchu]\r\n[ro.hardware.audio.primary]: [goldfish]\r\n[ro.hardware.power]: [ra
nchu]\r\n[ro.kernel.PARTUUID]: [2E462C39-3D23-47CD-8237-81CCBB79B58F]\r\n[ro.ker
nel.android.checkjni]: [1]\r\n[ro.kernel.android.qemud]: [1]\r\n[ro.kernel.andro
idboot.android_dt_dir]: [/sys/bus/platform/devices/ANDR0001:00/properties/androi
d/]\r\n[ro.kernel.androidboot.hardware]: [ranchu]\r\n[ro.kernel.androidboot.seri
alno]: [EMULATOR29X0X11X0]\r\n[ro.kernel.androidboot.verifiedbootstate]: [orange
]\r\n[ro.kernel.androidboot.veritymode]: [enforcing]\r\n[ro.kernel.clocksource]:
 [pit]\r\n[ro.kernel.cma]: [288M@0-4G]\r\n[ro.kernel.console]: [0]\r\n[ro.kernel
.dm]: ["1]\r\n[ro.kernel.init]: [/init]\r\n[ro.kernel.loop.max_part]: [7]\r\n[ro
.kernel.mac80211_hwsim.channels]: [2]\r\n[ro.kernel.mac80211_hwsim.mac_prefix]:
[5554]\r\n[ro.kernel.memmap]: [0x10000$0xff018000]\r\n[ro.kernel.ndns]: [4]\r\n[
ro.kernel.qemu]: [1]\r\n[ro.kernel.qemu.dalvik.vm.heapsize]: [384m]\r\n[ro.kerne
l.qemu.encrypt]: [1]\r\n[ro.kernel.qemu.gles]: [1]\r\n[ro.kernel.qemu.opengles.v
ersion]: [196609]\r\n[ro.kernel.qemu.settings.system.screen_off_timeout]: [21474
83647]\r\n[ro.kernel.qemu.uirenderer]: [skiagl]\r\n[ro.kernel.qemu.wifi]: [1]\r\
n[ro.kernel.ramoops.mem_address]: [0xff018000]\r\n[ro.kernel.ramoops.mem_size]:
[0x10000]\r\n[ro.kernel.root]: [/dev/dm-0]\r\n[ro.logd.size.stats]: [64K]\r\n[ro
.opengles.version]: [196609]\r\n[ro.product.board]: [goldfish_x86]\r\n[ro.produc
t.brand]: [google]\r\n[ro.product.cpu.abi]: [x86]\r\n[ro.product.cpu.abilist]: [
x86]\r\n[ro.product.cpu.abilist32]: [x86]\r\n[ro.product.cpu.abilist64]: []\r\n[
ro.product.device]: [generic_x86]\r\n[ro.product.first_api_level]: [28]\r\n[ro.p
roduct.locale]: [en-US]\r\n[ro.product.manufacturer]: [Google]\r\n[ro.product.mo
del]: [Android SDK built for x86]\r\n[ro.product.name]: [sdk_gphone_x86]\r\n[ro.
product.vendor.brand]: [google]\r\n[ro.product.vendor.device]: [generic_x86]\r\n
[ro.product.vendor.manufacturer]: [Google]\r\n[ro.product.vendor.model]: [Androi
d SDK built for x86]\r\n[ro.product.vendor.name]: [sdk_gphone_x86]\r\n[ro.proper
ty_service.version]: [2]\r\n[ro.revision]: [0]\r\n[ro.secure]: [1]\r\n[ro.serial
no]: [EMULATOR29X0X11X0]\r\n[ro.setupwizard.mode]: [DISABLED]\r\n[ro.treble.enab
led]: [true]\r\n[ro.vendor.build.date]: [Wed Apr 10 22:20:32 UTC 2019]\r\n[ro.ve
ndor.build.date.utc]: [1554934832]\r\n[ro.vendor.build.fingerprint]: [google/sdk
_gphone_x86/generic_x86:9/PSR1.180720.093/5456446:userdebug/dev-keys]\r\n[ro.ven
dor.build.security_patch]: []\r\n[ro.vndk.version]: [28]\r\n[ro.wifi.channels]:
[]\r\n[ro.zygote]: [zygote32]\r\n[security.perf_harden]: [1]\r\n[selinux.restore
con_recursive]: [/data/misc_ce/0]\r\n[service.bootanim.exit]: [1]\r\n[service.sf
.present_timestamp]: [0]\r\n[sys.boot.reason]: [reboot]\r\n[sys.boot_completed]:
 [1]\r\n[sys.logbootcomplete]: [1]\r\n[sys.rescue_boot_count]: [1]\r\n[sys.retai
ldemo.enabled]: [0]\r\n[sys.sysctl.extra_free_kbytes]: [24300]\r\n[sys.sysctl.tc
p_def_init_rwnd]: [60]\r\n[sys.uidcpupower]: []\r\n[sys.usb.config]: [adb]\r\n[s
ys.usb.configfs]: [0]\r\n[sys.usb.state]: [adb]\r\n[sys.user.0.ce_available]: [t
rue]\r\n[sys.wifitracing.started]: [1]\r\n[tombstoned.max_tombstone_count]: [50]
\r\n[vendor.qemu.dev.bootcomplete]: [1]\r\n[vold.decrypt]: [trigger_restart_fram
ework]\r\n[vold.has_adoptable]: [1]\r\n[vold.has_quota]: [1]\r\n[vold.has_reserv
ed]: [1]\r\n[vold.post_fs_data_done]: [1]\r\n[wifi.direct.interface]: [p2p-dev-w
lan0]\r\n[wifi.interface]: [wlan0]\r\n[xmpp.auto-presence]: [true]\r\n',
  stderr: '' }
Error: Command failed: C:\Users\admin\AppData\Local\Android\Sdk\platform-tools/a
db -s emulator-5554 shell getprop

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
[ERROR] An error occurred while running subprocess native-run.

        native-run.cmd android --app
        platforms\android\app\build\outputs\apk\debug\app-d... exited with exit
        code 1.

**Comment by dwieeb** [comment] 2019-06-10 18:36
Duplicate of https://github.com/ionic-team/native-run/issues/45

**Closed by dwieeb** 2019-06-10 18:36 UTC
